### ISSUE TITLE
Trouble with Exceptions

### ISSUE THREAD

**Issue by marcaddeo** [danslo/LibraryRewrite#1]
Hi there,

Just coming across this because I'm trying to use the `AoE_AmazonCdn` exception, and am having trouble getting it working.

It seems to me there's a problem with this library..

The problem I'm having is I go to upload an image to a catalog product, and when I hit save I get this error:

```
Fatal error: Class 'Magento\Exception' not found in /var/www/web/var/tmp/library_rewrite/2934697358.php on line 414
```

That line contains the following code: 

```
throw new Exception('Unable to list current working directory.');
```

So, it's trying to use `Magento\Exception` since we're in the namespace `Magento` for this file.

It seems your library_rewrite isn't escaping things to the global namespace when required. For instance it should probably be:

```
throw new \Exception('Unable to list current working directory.');
```

Or have a `use` statement at the beginning of the file.

Any ideas to solve this? It seems like the `AoE_AmazonCdn` plugin is popular, so I'm not quite sure why this doesn't work.

**Comment by marcaddeo** [comment]
Further review of the code shows there's also a line that throws a `new Varien_Io_Exception` that I'm assuming would cause a Fatal error as well since `Magento\Varien_Io_Exception` isn't going to exist.

Seems like there should probably be a regular expression involved that finds all instances of `new className` and replaces it with `new \className` to get it back into global scope, or use `use` statements at the beginning of the file?

**Comment by marcaddeo** [comment]
This seems like there may be even more to it, for example it doesn't handle constants like `DIRECTORY_SEPARATOR` either.

Maybe regular expressions aren't the way to approach this? Are you using this in production anywhere? Maybe I'm just not doing something right...

**Comment by danslo** [comment]
@marcaddeo For some reason I am not seeing e-mail notifications for this repository, so sorry for being slow on this.

I can't find [that code](https://github.com/AOEpeople/Aoe_AmazonCdn/search?q=Unable+to+list) in AoE_AmazonCdn. Can you provide some sample code to reproduce this?

As far as I know this shouldn't be happening as long as you're not adding your own class rewrites. And if you are, I'd like to see them.

**Comment by marcaddeo** [comment]
That code is in the `Varien_Io` class

**Comment by danslo** [comment]
I think I see the problem, but like the source suggests it's probably best to get rid of the regex at this point anyway.

I'll come up with a solution that uses `token_get_all` instead at some point later this week.

**Comment by danslo** [comment]
Sorry for the delay, I've been playing around with https://github.com/nikic/PHP-Parser to make this even cleaner...

**Comment by marcaddeo** [comment]
That looks like a great solution for this to tokenize each statement!

For now, I forked the Amazon_Cdn repository and removed the library_rewrite stuff. Now having unrelated problems with it ;)

**Comment by marcaddeo** [comment]
Hey @danslo have you gotten a chance to do any work on this?
